name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Firebase Config
        run: |
          mkdir -p js
          echo "export const firebaseConfig = {" > js/firebase-config.js
          echo "  apiKey: \"${{ secrets.VUE_APP_API_KEY }}\"," >> js/firebase-config.js
          echo "  authDomain: \"${{ secrets.VUE_APP_AUTH_DOMAIN }}\"," >> js/firebase-config.js
          echo "  projectId: \"${{ secrets.VUE_APP_PROJECT_ID }}\"," >> js/firebase-config.js
          echo "  storageBucket: \"${{ secrets.VUE_APP_STORAGE_BUCKET }}\"," >> js/firebase-config.js
          echo "  messagingSenderId: \"${{ secrets.VUE_APP_MESSAGING_SENDER_ID }}\"," >> js/firebase-config.js
          echo "  appId: \"${{ secrets.VUE_APP_APP_ID }}\"" >> js/firebase-config.js
          echo "};" >> js/firebase-config.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
