name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Firebase Config from Template
        run: |
          cp js/firebase-config.template.js js/firebase-config.js
          sed -i 's|__API_KEY__|${{ secrets.VUE_APP_API_KEY }}|g' js/firebase-config.js
          sed -i 's|__AUTH_DOMAIN__|${{ secrets.VUE_APP_AUTH_DOMAIN }}|g' js/firebase-config.js
          sed -i 's|__PROJECT_ID__|${{ secrets.VUE_APP_PROJECT_ID }}|g' js/firebase-config.js
          sed -i 's|__STORAGE_BUCKET__|${{ secrets.VUE_APP_STORAGE_BUCKET }}|g' js/firebase-config.js
          sed -i 's|__MESSAGING_SENDER_ID__|${{ secrets.VUE_APP_MESSAGING_SENDER_ID }}|g' js/firebase-config.js
          sed -i 's|__APP_ID__|${{ secrets.VUE_APP_APP_ID }}|g' js/firebase-config.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
